# Generated by Django 2.1.4 on 2019-01-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(max_length=11)),
                ('event', models.TextField()),
                ('weekday', models.TextField()),
                ('calendarblocked', models.TextField()),
                ('invitation_frequency', models.IntegerField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('mail', models.CharField(max_length=50)),
                ('passw', models.TextField()),
                ('location', models.TextField()),
                ('division', models.TextField()),
                ('department', models.TextField()),
            ],
        ),
    ]
