# Generated by Django 2.1.4 on 2019-01-12 06:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_datelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='datelog',
            name='eventid',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
